# Generated by Django 4.0.5 on 2022-07-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_joiners_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(max_length=200),
        ),
    ]
